### PR TITLE
chore(driver): use databend docker image do some test

### PR DESCRIPTION
**Pull request by TCeason**

### CODE REVIEW

**Comment by TCeason** [comment]
cc @hantmac @everpcpc  Please review this pr.

**Comment by hantmac** [comment]
> cc @hantmac @everpcpc Please review this pr.

@TCeason The CI failed because the `DatabendClientV1.discoverNodes(client, settings);` depends on the new feature in databend query, maybe the stable version of docker image does not contains this feature.

**Comment by TCeason** [comment]
> > cc @hantmac @everpcpc Please review this pr.
> 
> 
> 
> @TCeason The CI failed because the `DatabendClientV1.discoverNodes(client, settings);` depends on the new feature in databend query, maybe the stable version of docker image does not contains this feature.  

Get

**Comment by hantmac** [comment]
So I close this pr because the jdbc need the new feature.

**Pull request closed without merging**
