### PR TITLE
Fix getDatabaseMajorVersion & getDatabaseMinorVersion

### PR DESCRIPTION
**Pull request by rad-pat**
Just match RegEx in Full string "Databend Query vx.y.zzz" or "DatabendQuery vx.y.zzz"
Fixes https://github.com/datafuselabs/databend-jdbc/issues/204

### CODE REVIEW

**Comment by hantmac** [comment]
@rad-pat Thanks for your contribution. How about adding some unit tests for the modified function?

**Comment by rad-pat** [comment]
@hantmac, I can try. It looked like it was partially covered by a test already, but now I can see why that was incorrectly passing (because it always matched the "-1" version to string "rust-1"). I've made the test more specific for the version. Hope it works, I cannot get the tests to run locally for some reason.

**Comment by rad-pat** [comment]
Should be fixed now. It'd really help if I could run the tests, but the MetaData tests fail with this for me. I'm running against a locally installed Databend instance with user `root` and no password, on port 8100. I have to adjust the user/pwd/port in tests, but all other seem to work. If you have any ideas, I'd appreciate it.
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.databend.jdbc.TestDatabendDatabaseMetaData
Tests run: 16, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 2.057 sec <<< FAILURE! - in com.databend.jdbc.TestDatabendDatabaseMetaData
setUp(com.databend.jdbc.TestDatabendDatabaseMetaData)  Time elapsed: 1.848 sec  <<< FAILURE!
java.lang.RuntimeException: Query failed: Optional[{"error":{"code":"401","message":"No authorization header detected"}}]
	at com.databend.client.DatabendClientV1.executeInternal(DatabendClientV1.java:185)
	at com.databend.client.DatabendClientV1.execute(DatabendClientV1.java:206)
	at com.databend.client.DatabendClientV1.<init>(DatabendClientV1.java:91)
	at com.databend.jdbc.DatabendConnection.startQuery(DatabendConnection.java:588)
	at com.databend.jdbc.DatabendConnection.setSchema(DatabendConnection.java:473)
	at com.databend.jdbc.DatabendConnection.<init>(DatabendConnection.java:82)
	at com.databend.jdbc.NonRegisteringDatabendDriver.connect(NonRegisteringDatabendDriver.java:64)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.databend.jdbc.TestDatabendDatabaseMetaData.createConnection(TestDatabendDatabaseMetaData.java:80)
	at com.databend.jdbc.TestDatabendDatabaseMetaData.setUp(TestDatabendDatabaseMetaData.java:63)
```

**Comment by hantmac** [comment]
> Should be fixed now. It'd really help if I could run the tests, but the MetaData tests fail with this for me. I'm running against a locally installed Databend instance with user `root` and no password, on port 8100. I have to adjust the user/pwd/port in tests, but all other seem to work. If you have any ideas, I'd appreciate it.
> 
> ```
> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> Running com.databend.jdbc.TestDatabendDatabaseMetaData
> Tests run: 16, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 2.057 sec <<< FAILURE! - in com.databend.jdbc.TestDatabendDatabaseMetaData
> setUp(com.databend.jdbc.TestDatabendDatabaseMetaData)  Time elapsed: 1.848 sec  <<< FAILURE!
> java.lang.RuntimeException: Query failed: Optional[{"error":{"code":"401","message":"No authorization header detected"}}]
> 	at com.databend.client.DatabendClientV1.executeInternal(DatabendClientV1.java:185)
> 	at com.databend.client.DatabendClientV1.execute(DatabendClientV1.java:206)
> 	at com.databend.client.DatabendClientV1.<init>(DatabendClientV1.java:91)
> 	at com.databend.jdbc.DatabendConnection.startQuery(DatabendConnection.java:588)
> 	at com.databend.jdbc.DatabendConnection.setSchema(DatabendConnection.java:473)
> 	at com.databend.jdbc.DatabendConnection.<init>(DatabendConnection.java:82)
> 	at com.databend.jdbc.NonRegisteringDatabendDriver.connect(NonRegisteringDatabendDriver.java:64)
> 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
> 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
> 	at com.databend.jdbc.TestDatabendDatabaseMetaData.createConnection(TestDatabendDatabaseMetaData.java:80)
> 	at com.databend.jdbc.TestDatabendDatabaseMetaData.setUp(TestDatabendDatabaseMetaData.java:63)
> ```

@rad-pat Hi I add you to the github action CI, the CI will run auto when you push.

**Review by hantmac — APPROVED** [review]
/LGTM

**Pull request merged**
